import StyleDictionary from "style-dictionary";

const PREFIX = "pumba-primitive";

// Emits one ESM module and one declaration file, so consumers get autocomplete on token names.
StyleDictionary.registerFormat({
  name: "pumba/ts-module",
  format: ({ dictionary }) => {
    const entries = dictionary.allTokens.map((token) => [token.name, `var(--${token.name})`]);
    const body = entries.map(([name, ref]) => `  ${JSON.stringify(name)}: ${JSON.stringify(ref)},`);
    return [
      "// Generated by build.mjs. Do not edit.",
      "export const primitives = {",
      ...body,
      "};",
      "",
    ].join("\n");
  },
});

StyleDictionary.registerFormat({
  name: "pumba/ts-declarations",
  format: ({ dictionary }) => {
    const names = dictionary.allTokens.map((token) => `  | ${JSON.stringify(token.name)}`);
    return [
      "// Generated by build.mjs. Do not edit.",
      "export type PrimitiveTokenName =",
      ...names,
      ";",
      "",
      "export declare const primitives: Readonly<Record<PrimitiveTokenName, string>>;",
      "",
    ].join("\n");
  },
});

const sd = new StyleDictionary({
  source: ["src/**/*.json"],
  platforms: {
    css: {
      transformGroup: "css",
      prefix: PREFIX,
      buildPath: "dist/",
      files: [
        {
          destination: "tokens.css",
          format: "css/variables",
          options: { selector: ":root", outputReferences: false },
        },
      ],
    },
    ts: {
      transformGroup: "css",
      prefix: PREFIX,
      buildPath: "dist/",
      files: [
        { destination: "index.js", format: "pumba/ts-module" },
        { destination: "index.d.ts", format: "pumba/ts-declarations" },
      ],
    },
  },
});

await sd.buildAllPlatforms();
